[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hex_to_base_64"

[[bin]]
name = "fixed_xor"

[[bin]]
name = "single_byte_xor"

[[bin]]
name = "single_character_xor"

[[bin]]
name = "repeating_key_xor"

[dependencies]